### ISSUE TITLE
Handle error 187 (duplicated item)

### ISSUE THREAD

**Issue by facundobianco** [vando/news2tw#2]
Bad handling error 187 and/or inverse parsing on newest news.

```
DEBUG:root:  ERR 187: Status is a duplicate.. Quit.
DEBUG:root:  Continue.
Traceback (most recent call last):
  File "news2tw.py", line 429, in <module>
    main()
  File "news2tw.py", line 388, in main
    if data['err326'] == True:
KeyError: 'err326'
```

**Comment by facundobianco** [comment]
Issue came from error 326 that wasn't added in configuration file
